AllCops:
  # @see https://docs.rubocop.org/rubocop/configuration.html#pre-processing
  Exclude:
    - .yardoc/
    - coverage/
    - doc/
    - config/**/*

  NewCops: enable
  TargetRubyVersion: 3.4

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety
  - rubocop-md

Naming/MethodName:
  Enabled: false

Naming/FileName:
  Enabled: false

# Check with yard instead.
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Include:
    - app/**/*

  Exclude:
      - test/**/*
      - config/**/*

Style/RedundantConstantBase:
  Enabled: false

Style/EachForSimpleLoop:
  Enabled: false

# Use CamelCase for any constants (classes, modules, constants)
Naming/ConstantName:
  Enabled: false






Lint/ConstantResolution:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/ClassLength:
  Enabled: false

# Use CamelCase for any constants (classes, modules, constants)
Naming/ConstantName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/EmptyMethod:
  EnforcedStyle: expanded

# As long as we don't need to use a version lower or equal to 1.9, we can use the new syntax.
Style/SymbolArray:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
